name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Télécharger le projet
      uses: actions/checkout@v4

    - name: ⚙️ Installer les dépendances
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip python3-setuptools
        pip install buildozer==1.5.0 cython==0.29.36

    - name: 🏗️ Construire APK
      run: |
        buildozer init

        sed -i 's/title = .*/title = Produit App/' buildozer.spec
        sed -i 's/package.name = .*/package.name = produitapp/' buildozer.spec
        sed -i 's/requirements = .*/requirements = python3,kivy/' buildozer.spec
        sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
        sed -i 's/warn_on_root = 1/warn_on_root = 0/' buildozer.spec

        buildozer -v android debug

    - name: 📦 Envoyer APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
